@startuml
package "Tracker Detector" {
    interface gql as "Graph QL API" 
    database db as "Database"
    component chrome_ext as "Chrome Extension"
    component frontend as "Frontend"
    component backend as "Backend"
}

database cookie_ref as "External Tracker\nKnowledge Database"

[backend] -up- gql
[frontend] --( gql
[chrome_ext] --( gql
[backend] - db
[backend] --( cookie_ref
@enduml
